services:
  jmeter:
    image: jmeter
    volumes:
      - /root/jmeter/apache-jmeter-5.6.3/bin:/opt/apache-jmeter-5.6.3/bin
      - /root/Results:/opt/apache-jmeter-5.6.3/bin/testResults
    command: ["-n", "-t", "bin/examples/CSVSample.jmx", "-l", "bin/testResults/Run1.jtl"]
volumes:
  jmeter:
