version: '3'
services:
  jmeter:
    image: jmeter
    volumes:
      - jmeter:/opt/apache-jmeter-5.6.3/bin
    command: ["-n", "-t", "bin/examples/CSVSample.jmx", "-l", "./bin/examples/Run1.jtl"]
volumes:
  jmeter:
